.nh
.TH NBFC\_SERVICE 1 "MARCH 2021" Notebook FanControl
.SH NAME
.PP
nbfc\_service \- Notebook FanControl service

.SH DESCRIPTION
.PP
Probing tool for embedded controllers

.SH SYNOPSIS
.PP
\fB\fCec\_probe\fR [OPTIONS]

.SH OPTIONS
.PP
\fB\fC\-h, \-\-help\fR
    show this help message and exit

.PP
\fB\fC\-e, \-\-embedded\-controller EC [ec\_linux, ec\_sys\_linux, ec\_acpi]\fR
    Specify embedded controller to use

.PP
\fB\fC[dump, read, write, monitor]\fR
    None

.SH COMMANDS
.PP
dump, read, write, monitor

.SH DESCRIPTION
.PP
Dump all EC registers

.SH SYNOPSIS
.PP
\fB\fCdump\fR [OPTIONS]

.SH OPTIONS
.PP
\fB\fC\-h, \-\-help\fR
    show this help message and exit

.SH DESCRIPTION
.PP
Read a byte from a EC register

.SH SYNOPSIS
.PP
\fB\fCread\fR [OPTIONS]

.SH OPTIONS
.PP
\fB\fC\-h, \-\-help\fR
    show this help message and exit

.PP
\fB\fCREGISTER [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, ...]\fR
    Register source

.SH DESCRIPTION
.PP
Write a byte to a EC register

.SH SYNOPSIS
.PP
\fB\fCwrite\fR [OPTIONS]

.SH OPTIONS
.PP
\fB\fC\-h, \-\-help\fR
    show this help message and exit

.PP
\fB\fCREGISTER [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, ...]\fR
    Register destination

.PP
\fB\fCVALUE [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, ...]\fR
    Value to write

.SH DESCRIPTION
.PP
Monitor all EC registers for changes

.SH SYNOPSIS
.PP
\fB\fCmonitor\fR [OPTIONS]

.SH OPTIONS
.PP
\fB\fC\-h, \-\-help\fR
    show this help message and exit

.PP
\fB\fC\-i, \-\-interval seconds\fR
    Monitored timespan

.PP
\fB\fC\-t, \-\-timespan seconds\fR
    Set poll intervall

.PP
\fB\fC\-r, \-\-report str\fR
    Save all readings as a CSV file

.PP
\fB\fC\-c, \-\-clearly\fR
    Blanks out consecutive duplicate readings

.PP
\fB\fC\-d, \-\-decimal\fR
    Output readings in decimal format instead of hexadecimal format

.PP
All input values are interpreted as decimal numbers by default.
Hexadecimal values may be entered by prefixing them with "0x".
